name: GitHub Actions CI (AMD)

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "src/**"
    #   - "test/**"

concurrency:
  # This causes it to cancel previous in-progress actions on the same PR / branch,
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black

    - name: Run checkstyle
      run: make checkstyle

  tests:
    runs-on: linux-mi300-gpu-1
    needs: [checkstyle]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Check Docker Version
      run: docker version

    - name: Build Liger-Kernel CI Docker image
      run: docker build -t liger-kernel-ci -f Dockerfile.rocm .

    - name: Run the tests
      run: |
        sudo docker run \
          --network=host \
          --group-add=video \
          --ipc=host \
          --cap-add=SYS_PTRACE \
          --security-opt seccomp=unconfined \
          --device /dev/kfd \
          --device /dev/dri \
          liger-kernel-ci \
          /bin/bash -c "make test; make test-convergence"
