name: GitHub Actions CI (AMD)

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "src/**"
    #   - "test/**"

concurrency:
  # This causes it to cancel previous in-progress actions on the same PR / branch,
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black
    - name: Run checkstyle
      run: make checkstyle

  tests:
    runs-on: linux-mi300-gpu-1
    needs: [checkstyle]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Check Docker Version
      run: docker version

    - name: Setup Dependencies
      run: |
        cp -r /opt/rocm/share/amd_smi ./
        cd amd_smi
        python3 -m pip install -e .
        cd ..
        python3 -m pip uninstall -y torch torchvision
        python3 -m pip install --pre \
                torch==2.6.0.dev20241122+rocm6.2 \
                'setuptools-scm>=8' \
                torchvision==0.20.0.dev20241122+rocm6.2 \
                --extra-index-url https://download.pytorch.org/whl/nightly/rocm6.2
        python3 -m pip install triton==3.1.0 transformers==4.46.3
        python3 -m pip install -e .[dev]
    
    - name: Run Unit Tests
      run: |
        make test
        make test-convergence
