name: GitHub Actions CI (AMD)

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "src/**"
    #   - "test/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black

    - name: Run checkstyle
      run: make checkstyle

  tests:
    runs-on: linux-mi300-gpu-1
    needs: [checkstyle]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Check Docker Version
      run: docker version

    - name: Run the tests in Docker
      run: |
        sudo docker run \
          --network=host \
          --group-add=video \
          --ipc=host \
          --cap-add=SYS_PTRACE \
          --security-opt seccomp=unconfined \
          --device /dev/kfd \
          --device /dev/dri \
          -v ${{ github.workspace }}:/liger-kernel-workspace \
          ghcr.io/embeddedllm/liger-kernel-ci:rocm6.2.3_ubuntu22.04_py3.10_pytorch2.6.0.dev20241113_triton_llvm_reg_issue_hipblaslt0.8 \
          /bin/bash -c "cd /liger-kernel-workspace && python -m pip install -e .[dev] && make test-convergence"